a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
y = (a * f - c * e) / (a * d - b * c)
x = (e * d - b * f) / (a * d - b * c)
print(x, y)
